# define the execution user globally
run_as shiny;


# Tell Shiny Server to look for configuration options on all interfaces on port 7860
server {
  listen 7860 0.0.0.0;

  # Define the directory where the shiny apps will be hosted inside the container
  location / {
    site_dir /srv/shiny-server;
    log_dir /var/log/shiny-server;
    directory_index on;
  }
}